"use client"
import dynamic from "next/dynamic";
import AddonDetailTemplate from "@/components/AddonDetailTemplate";
import InfoMediaTwoColumn from "@/components/InfoMediaTwoColumn";
import SectionHeader from "@/components/SectionHeader";
import VideoGrid from "@/components/VideoGrid";
import CDSLicenseInfoSection from "@/components/CDSLicenseInfoSection";
const ImageGallery = dynamic(() => import("@/components/ImageGallery"), { ssr: false });
import Image from "next/image";
import { Card } from "@/components/ui/card";
import { icons, galleryImages as rawGalleryImages } from "@/assets/solutions/cds/3d-dimensioning/images";
import imgLicense from "@/assets/solutions/cds/drive-curve/islevsel-genel-bakis/Lizenz-anzeigen.webp";
export default function ClientPage() {
  const galleryImages = rawGalleryImages.map((src, idx) => ({ id: `ex-${idx}`, src, alt: `Müşteri örneği ${idx + 1}`, title: "Müşteri örneği", description: "", category: "örnek" }));
  const features = [{ titleTr: "Masslinie erzeugen" },{ titleTr: "Kotenbemassung erzeugen" },{ titleTr: "Winkelbemassung erzeugen" },{ titleTr: "Gefällebemassung erzeugen" },{ titleTr: "Höhenkote erzeugen" },{ titleTr: "Kreisbemassung erzeugen" },{ titleTr: "Textzeiger erzeugen" },{ titleTr: "Referenz-Punkt hinzufügen" },{ titleTr: "Referenz-Punkt löschen" },{ titleTr: "Referenz-Punkt verschieben" },{ titleTr: "Masslinie verschieben" },{ titleTr: "Text verschieben" },{ titleTr: "Textposition zurücksetzen" },{ titleTr: "Symbol modifizieren" },{ titleTr: "Masslinie aktualisieren" },{ titleTr: "Eigenschaften übertragen" },{ titleTr: "Masslinie modifizieren" },{ titleTr: "Bemassung löschen" }];
  const sections = [
    <InfoMediaTwoColumn key="hero" title="3B Ölçülendirme" subtitle="3D Bemassung" descriptions={["Allplan için 3B ölçülendirme eklentisi, modellerinizi veya perspektiflerinizi sunmak için ideal bir eklentidir. Objelerinizi doğrudan boş alanda ölçün.","","3D ölçülendirme ile modeliniz hassasiyet ve netlik kazanır. Örneğin, gerçek uzunlukları, eğimleri, yükseklikleri, açıları veya koordinatları ölçülendirebilirsiniz. Bu, planlamanızı herkes için anlaşılır kılar ve aynı zamanda yanlış anlamaları önler."]} videoUrl="https://www.youtube.com/embed/GlkCJ9hmqho" />,
    <section key="features" className="py-16 bg-gradient-to-br from-slate-50 to-accent/10"><div className="container mx-auto px-4 sm:px-6 lg:px-8"><SectionHeader title="Fonksiyona genel bakış:" align="center" className="py-0 bg-transparent mb-12" compact titleSize="lg" /><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-4">{features.map((feature, idx) => (<Card key={idx} className="p-4 flex flex-col items-center text-center hover:shadow-technical transition-all">{icons[idx] && (<Image src={icons[idx]} alt={feature.titleTr} className="mb-3 object-contain" width={96} height={96} />)}<h3 className="text-xs font-semibold text-gray-800 leading-tight">{feature.titleTr}</h3></Card>))}</div></div></section>,
    <section key="properties" className="py-16 bg-background"><div className="container mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto"><h2 className="text-3xl font-bold text-gray-900 mb-8"><span>Özellikler</span></h2><ul className="space-y-3 text-gray-700"><li className="flex items-start"><span className="mr-2">•</span><span>Sezgisel olarak öğrenilebilir</span></li><li className="flex items-start"><span className="mr-2">•</span><span>Uzayda 3B boyutlar</span></li><li className="flex items-start"><span className="mr-2">•</span><span>Dinamik önizlemeler</span></li><li className="flex items-start"><span className="mr-2">•</span><span>Favorileri kaydedin ve yükleyin</span></li><li className="flex items-start"><span className="mr-2">•</span><span>Ölçü çizgileri, seviyeler, açı, koordinat ve eğim boyutları</span></li><li className="flex items-start"><span className="mr-2">•</span><span>Yarıçap, çap ve yay boyutlarıyla daire boyutları</span></li><li className="flex items-start"><span className="mr-2">•</span><span>Koordinat listeleri oluşturun</span></li><li className="flex items-start"><span className="mr-2">•</span><span>Boyutlarla kesitler, görünümler ve perspektifler elde edin</span></li><li className="flex items-start"><span className="mr-2">•</span><span>BIM süreci için ek özellikler</span></li><li className="flex items-start"><span className="mr-2">•</span><span>3B PDF / IFC / BIMPLUS&apos;u ölçülerle dışa aktarın</span></li></ul></div></div></section>,
    <VideoGrid key="demo-videos" items={[{ youtubeId: "GlkCJ9hmqho", title: "Demo Video 1" },{ youtubeId: "IR6TsiCpPJI", title: "Demo Video 2" },{ youtubeId: "Z8-aMd_TGBY", title: "Demo Video 3" }]} />,
    <section key="customer-examples" className="py-16 bg-gradient-to-br from-slate-50 to-accent/10"><div className="container mx-auto px-4 sm:px-6 lg:px-8"><SectionHeader title="Müşteri örnekleri" align="center" className="py-0 bg-transparent mb-12" compact titleSize="lg" /><InfoMediaTwoColumn title="" subtitle="" descriptions={["3B ölçülendirme eklentisi şu anda 300 Allplan kullanıcısı tarafından kullanılmaktadır ve 10 dilde mevcuttur. Uygulama alanları, ofislerin farklı görevleri kadar çeşitlidir."]} videoUrl="https://www.youtube.com/embed/Z8-aMd_TGBY" /><ImageGallery images={galleryImages} sectionTitle="Müşteri örnekleri" sectionDescription="Gerçek projelerden 3B ölçülendirme örnekleri" /></div></section>,
    <CDSLicenseInfoSection key="license-info" title="Lisans ve Gereksinimler" subtitle="Tek kullanıcı lisansı, mevcut Allplan lisansına bağlıdır ve bir PC'den diğerine kolayca aktarılabilir." description="Eklentiyi yükledikten sonra deneme sürümünü 14 gün ücretsiz olarak kullanabilirsiniz." systemRequirements="Allplan 2020 – 2023" languages="Almanca, İngilizce ve İtalyanca" imageUrl={imgLicense} imageAlt="Lisans" links={[{ text: "Çoklu Kurulum ile Kurulum Kılavuzu", url: "https://youtu.be/BWKDmZyIUo4", variant: "link" },{ text: "Link zum Download Bereich (Setup)", url: "https://cdssieber.sharepoint.com/:f:/g/Ev_G2db5WVVBvMEN-Adhz24Bk5f3rEvFCQu77iLTTCIynw?e=qkPdri", variant: "default" }]} quoteFormUrl="https://forms.office.com/r/XLQm9JPTSR" quoteFormText="Başvuru Formu İçin Tıklayın" />,
  ];
  return <AddonDetailTemplate title="3B Ölçülendirme" subtitle="3D Bemassung" description="3B modellerinizi hassas ölçülerle sunun - Uzayda doğrudan ölçülendirme" sections={sections} />;
}
