"use client"
import EnhancedSolutionTemplate from "@/components/EnhancedSolutionTemplate";
import SolutionHero from "@/components/SolutionHero";
import InfoMediaTwoColumn from "@/components/InfoMediaTwoColumn";
import imgWorkflow from "@/assets/solutions/structural/workflows/modeling/parametric-modeling.jpg";

export default function ClientPage() {
  const introParagraphs = [
    "The geometry of precast girders is governed by the geometry of the substructure and their position along the axis. Thus, a further modeling approach is available in Allplan Bridge that enables users to create an exact geometry of precast girder bridges easily and quickly.",
    "The modeling process is optimized even further by using parametric 3D templates. In this way repetitive bridge elements, such as straight precast girders, have to be defined only once and then placed parametrically as many times as necessary.",
  ];
  const workflowItems = [
    {
      title: "1. CREATING AXES",
      description:
        "Every bridge construction project starts with one or more axes – with Allplan Bridge, you can adopt the data from an existing design (using LandXML data format) or define it manually. In both cases, the alignment is parametrically saved.",
      videoUrl: "https://www.youtube.com/embed/2uFnK6J2GsU",
    },
    {
      title: "2. DEFINING A CROSS-SECTION",
      description:
        "You can define any cross-section and determine the geometry with its dependencies and variables. These parametric cross-sections can be adapted at any time and can be saved as a template and reused.",
      videoUrl: "https://www.youtube.com/embed/dwnGswjBZBg",
    },
    {
      title: "3. DESIGNING A TEMPLATE",
      description:
        "Any geometry of a pier, foundation and precast girder can be defined as a template. Previously defined cross-section(s) including constant and variable parameters are used. You can set which parts should be fixed and which should adjust when using it in the 3D model.",
      videoUrl: "https://www.youtube.com/embed/ZRqoMOCb11U",
    },
    {
      title: "4. BUILDING A SUBSTRUCTURE",
      description:
        "The substructure, with or without foundations, can be defined relative to one axis or relative to two axes – for example terrain axis at the bottom and road axis at the top. It can be defined directly or by usage of templates.",
      videoUrl: "https://www.youtube.com/embed/LBIEi0bhOeQ",
    },
    {
      title: "5. ASSEMBLING GIRDERS",
      description:
        "For generating the plate geometry, the original workflow of Allplan Bridge is used – extruding the geometry along the axis. Variations can be used and the cross-section, and with this also the 3D model, can be equipped with all the details by using boundaries or placing python parts.",
      videoUrl: "https://www.youtube.com/embed/LFTDg95kvH4",
    },
    {
      title: "6. CONSTRUCTING A PLATE",
      description:
        "Extrude the geometry along the axis to construct the plate. Any variations can be applied and the cross-section, and with this also the 3D model, can be equipped with details, either by using boundaries or by placing python parts.",
      videoUrl: "https://www.youtube.com/embed/rqv66ghmUpk",
    },
    {
      title: "7. COMPOSING THE HAUNCH",
      description:
        "In precast girder bridges the shape of the girders is governed by the geometry of the substructure, whereas the geometry of the plate is governed by the axis. Allplan Bridge 3D Boolean operations automatically fill the space between the girder and plate using the haunch shape defined in the girder cross-section.",
      videoUrl: "https://www.youtube.com/embed/oqLafh87vYI",
    },
    {
      title: "8. COMPLETING THE BRIDGE STRUCTURE",
      description:
        "Once the main bridge elements are finished, further elements and details like tendons, diaphragms, bearings and many more can be generated by modeling them or by placing parametric elements – python parts.",
      videoUrl: "",
    },
  ];

  const preWorkflowSection = (
    <>
      {workflowItems.map((item) => (
        <InfoMediaTwoColumn
          key={item.title}
          title={item.title}
          description={item.description}
          imageSrc={imgWorkflow}
          videoUrl={item.videoUrl || undefined}
        />
      ))}
    </>
  );

  return (
    <EnhancedSolutionTemplate
      badge="BRIDGE ENGINEERING"
      title="MODELING OF PRECAST GIRDER BRIDGES"
      subtitle="Allplan Bridge – Dedicated workflow for precast girder bridges"
      description={`${introParagraphs[0]} ${introParagraphs[1]}`}
      customHero={
        <SolutionHero
          badge="BRIDGE ENGINEERING"
          title="MODELING OF PRECAST GIRDER BRIDGES"
          subtitle="Allplan Bridge – Dedicated workflow for precast girder bridges"
          description={`${introParagraphs[0]} ${introParagraphs[1]}`}
        />
      }
      showCta={false}
      preWorkflowSection={preWorkflowSection}
    />
  );
}
